/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.util.Scanner;
import java.sql.Date;

public class App {
    
  public static void main(String[] args) {
    
    Scanner keyboard = new Scanner(System.in);
    
    
    
    System.out.println("번호를 입력하세요.");
    int no = keyboard.nextInt();
    keyboard.nextLine();
    System.out.println("수업명을 입력하세요.");
    String name = keyboard.nextLine();
    System.out.println("설명을 입력하세요.");
    String description = keyboard.nextLine();
    System.out.println("시작일을 입력하세요.");
    Date startDate = Date.valueOf(keyboard.next());
    System.out.println("종료일을 입력하세요.");
    Date endDate = Date.valueOf(keyboard.next());
    System.out.println("총수업시간을 입력하세요.");
    int totalTime = keyboard.nextInt();
    keyboard.nextLine();
    System.out.println("일수업시간을 입력하세요.");
    int dayTime = keyboard.nextInt();
    keyboard.nextLine();
    
    keyboard.close();
    
    System.out.printf("번호: %d\n", no);
    System.out.printf("수업명: %s\n", name);
    System.out.printf("설명: %s\n", description);
    System.out.printf("시작일: %s\t  종료일: %s\n", startDate, endDate);
    System.out.printf("총수업시간: %d\n시간", totalTime);
    System.out.printf("일수업시간: %d\n시간", dayTime);
    
    keyboard.close();
  }
}
